from enum import Enum


class ProductStatus(str, Enum):
    INGESTED = "INGESTED"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    INVALID = "INVALID"
    UNDERSTOOD = "UNDERSTOOD"
    RESOLVED = "RESOLVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    CLASSIFIED = "CLASSIFIED"
    RESEARCHED = "RESEARCHED"
    NO_AUTHORITATIVE_SOURCE = "NO_AUTHORITATIVE_SOURCE"
    INDEXED = "INDEXED"
    EXTRACTED = "EXTRACTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NORMALIZED = "NORMALIZED"
    VALIDATED = "VALIDATED"
    PARTIAL = "PARTIAL"
    FAIL = "FAIL"
    APPROVED = "APPROVED"
